### PR TITLE
Update dependencies to batchgenerators>=0.21 

### PR DESCRIPTION
**Pull request by denbonte**
This should solve a fair share of dependency issues with other models that are based on `nnunet`.

### CODE REVIEW

**Comment by wasserth** [comment]
Thanks for the pull request. I thought there was a reason that I used version 0.21 of batchgenerators. But I am not 100% sure anymore. I have to check that and I will come back to you.

**Comment by denbonte** [comment]
No worries Jakob!

For reference, this will fix the error we showed today at the ProjectWeek presentation - and similar!

In this case, after installing `platipy[cardiac]`/specific versions of `nnunet` on the same system:

```
> Attempting uninstall: batchgenerators
>   Found existing installation: batchgenerators 0.24
>   Uninstalling batchgenerators-0.24:
>     Successfully uninstalled batchgenerators-0.24
> ERROR: pip's dependency resolver does not currently
  take into account all the packages that are 
  installed. This behaviour is the source of the 
  following dependency conflicts.
  nnunet 1.7.0 requires batchgenerators>=0.23, but you 
  have batchgenerators 0.21 which is incompatible.
```

**Comment by wasserth** [comment]
I just looked into it in more detail: Unfortunately this version requirement is needed since I am using an older nnUNet version with some minor modifications. This does not work with the newest batchgenerators. When the big rewrite of nnUNet is released I will see if I can update to this new version of nnUNet and then this batchgenerators version requirement can also be removed. Until then I would recommend installing TotalSegmentator in its own virtual python environment.

**Comment by denbonte** [comment]
Thanks for looking into it @wasserth - no worries!

**Pull request closed without merging**
