### PR TITLE
update SNOMED mapping to include v2 codes

### PR DESCRIPTION
**Pull request by fedorov**
See details related to the development of this mapping in https://github.com/lassoan/SlicerTotalSegmentator/pull/40

@wasserth related to this PR, per discussion with @lassoan in https://github.com/lassoan/SlicerTotalSegmentator/issues/42#issuecomment-1783518201, our understanding is that the actual numeric label used in the segmentation result depends on the specific task, and the column in the mapping document that corresponds to the numeric label may be misleading. Maybe it is better to drop that column altogether?

### CODE REVIEW

**Comment by wasserth** [comment]
Thanks for the update. Great work! Yes, the numeric label / ID column can be a bit misleading this way. Probably it is best to remove it. Do you want to update the PR?

**Comment by fedorov** [comment]
Yes, I will update the PR shortly - thank you!

**Comment by fedorov** [comment]
@wasserth done!

**Comment by wasserth** [comment]
Great! Thank you!

**Pull request merged**
