### PR TITLE
Package snomed mapping as a totalsegmentator package resource

### PR DESCRIPTION
**Pull request by jcfr**
* Organize snomed mapping resource into a `totalsegmentator` namespace package
* Ensure snomed mapping is installed alongside `totalsegmentator` package. See https://setuptools.pypa.io/en/latest/userguide/datafiles.html

To retrieve the location after installing `totalsegmentator`, the following may be done:

```python
from importlib.metadata import distribution
from pathlib import Path


def _lookup(path: str, optional: bool = False) -> Path | None:
    """Support editable installation by looking up path using distribution API."""
    files = distribution("idc_index_data").files
    if files is not None:
        for _file in files:
            if str(_file) == path:
                return Path(str(_file.locate())).resolve(strict=True)
    if optional:
        return None

    msg = f"Failed to lookup '{path}`."
    raise FileNotFoundError(msg)


TOTALSEGMENTATOR_SNOMED_MAPPING_FILEPATH: Path | None = _lookup("resources/totalsegmentator_snomed_mapping.csv")
```

We could also look into adding the code above directly into `totalsegmentator/__init__.py`

cc: @fedorov @lassoan

### CODE REVIEW

**Comment by jcfr** [comment]
For reference, here is the output reported when building the wheel locally:

**Comment by fedorov** [comment]
Very cool, thank you @jcfr! 🥇 

@wasserth for the background, the motivation for this is to make it easier to reuse this mapping by the users of the package. Currently, there is a duplicate out-of-sync mapping in SlicerTotalSegmentator extension. Jointly with #324 we are trying to consolidate and remove duplication to simplify maintenance.

**Comment by wasserth** [comment]
Thanks for this PR. This sounds reasonable. I am not very familiar with adding data files to the package. 
I read that when doing `include_package_data=True`, setuptools will include the files specified in MANIFEST.in in the package distribution. But in this case there is no MANIFEST.in file. So how does setuptools know that it has to add the snomed csv file?

**Comment by jcfr** [comment]
Thanks for the review :pray: 

> But in this case there is no MANIFEST.in file. So how does setuptools know that it has to add the snomed csv file?

This was on oversight[^1], the settings in `setup.py` was updated.

[^1]: While experimenting, I did not removed a previously created directory (`TotalSegmentator.egg-info`) which led me to over simplify the approach.

**Pull request merged**
